# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0010_pd2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pd1',
        ),
        migrations.DeleteModel(
            name='PosterData',
        ),
    ]
